apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa
  annotations:
    # This annotation is optional.
    # If specified, then this prometheus server is used,
    # instead of the prometheus server specified as the CLI argument `--prometheus-server`.
#    metric-config.external.processed-events-per-second.prometheus/prometheus-server: http://prom.default.svc.cluster.local
    # metric-config.<metricType>.<metricName>.<collectorType>/<configKey>
    metric-config.external.potato-queue-depth.prometheus/query: |
      avg(potato_queue_depth)
    metric-config.external.potato-queue-depth.prometheus/interval: "10s" # optional
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metric:
          name: potato-queue-depth
          selector:
            matchLabels:
              type: prometheus
        target:
#          type: AverageValue
#          averageValue: "100"
          type: Value
          value: 400
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Max